# Generated by Django 4.0 on 2021-12-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('hinchas', models.IntegerField()),
                ('esGrande', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('capacidad', models.IntegerField()),
                ('esGrande', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='esNoche',
            field=models.BooleanField(null=True),
        ),
    ]
